
target 'EShare' do
  use_frameworks!

pod 'SDWebImage'
pod 'SDAutoLayout'
pod 'TZImagePickerController'
pod 'FFToolModule’
pod 'BYToolModule’
pod 'LEEAlert'
pod 'MBProgressHUD'
pod 'WechatOpenSDK'

end
