
target 'EShare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod 'MJRefresh'
pod 'SDWebImage'
pod 'SwiftyUserDefaults'
pod 'SVProgressHUD'
pod 'SDAutoLayout'
pod 'TZImagePickerController'
pod 'FFToolModule’
pod 'BYToolModule’
pod 'LEEAlert'
pod 'MBProgressHUD'
pod 'WechatOpenSDK'

end
